Flow Controller:
  name: Invokehttp
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- name: GetFile
  class: org.apache.nifi.processors.standard.GetFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Batch Size: '10'
    File Filter: '[^\.].*'
    Ignore Hidden Files: 'true'
    Input Directory: /opt/minifi/minifi-1.19.1/in
    Keep Source File: 'false'
    Maximum File Age:
    Maximum File Size:
    Minimum File Age: 0 sec
    Minimum File Size: 0 B
    Path Filter:
    Polling Interval: 0 sec
    Recurse Subdirectories: 'true'
- name: InvokeHTTP
  class: org.apache.nifi.processors.standard.InvokeHTTP
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list:
  - Failure
  - No Retry
  - Original
  - Response
  - Retry
  Properties:
    Add Response Headers to Request: 'false'
    Always Output Response: 'false'
    Attributes to Send:
    Basic Authentication Password:
    Basic Authentication Username:
    Connection Timeout: 5 secs
    Content-Encoding: DISABLED
    Content-Type: ${mime.type}
    Digest Authentication: 'false'
    Follow Redirects: 'True'
    HTTP Method: POST
    Include Date Header: 'True'
    Max Length To Put In Attribute: '256'
    Penalize on "No Retry": 'false'
    Proxy Host:
    Proxy Port:
    Proxy Type: http
    Put Response Body In Attribute:
    Read Timeout: 15 secs
    Remote URL: http://<service-IP>:80/files
    SSL Context Service:
    Use Chunked Encoding: 'false'
    Useragent:
    cookie-strategy: DISABLED
    disable-http2: 'False'
    etag-max-cache-size: 10MB
    flow-file-naming-strategy: RANDOM
    form-body-form-name:
    idle-timeout: 5 mins
    ignore-response-content: 'false'
    invokehttp-proxy-password:
    invokehttp-proxy-user:
    max-idle-connections: '5'
    oauth2-access-token-provider:
    proxy-configuration-service:
    send-message-body: 'true'
    set-form-filename: 'true'
    use-etag: 'false'
Connections:
- name: GetFile/success/InvokeHTTP
  source name: GetFile
  source relationship name: success
  destination name: InvokeHTTP
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Processing Groups: []
