apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  clusterIP: 10.102.56.110
  clusterIPs:
  - 10.102.56.110
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run : my-nginx